config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'articles#index'
  get 'articles/search'

  resources :relationships

  resources :users, only: [:show, :edit, :update] do
    resources :favorites
    member do
      get :follow, :followers
    end
  end

  resources :articles do
    resources :goodjobs
  end
  post '/relationship/:follow_id', to: 'relationships#create', as: 'follow'
  post '/favorite/:article_id', to: 'favorites#create', as: 'love'
  delete '/favorite/:article_id', to: 'favorites#destroy', as: 'unlove'
  post 'articles/attach', to: 'articles#attach'
  post '/goodjob/:article_id', to: 'goodjobs#create', as: 'like'
  delete '/goodjob/:article_id', to: 'goodjobs#destroy', as: 'unlike'
end

app/models/goodjob.rb
class Goodjob < ApplicationRecord
  belongs_to :article, counter_cache: :goodjobs_counts
  belongs_to :user
end

app/controllers/goodjobs_controller.rb
class GoodjobsController < ApplicationController
  before_action :set_article

  def create
    @goodjob = Goodjob.create(user_id: current_user.id, article_id: @article.id)
    @goodjobs = Goodjob.where(article_id: params[:article_id])
    @articles = Article.all
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def destroy
    @goodjob = Goodjob.find_by(user_id: current_user.id, article_id: @article.id)
    @goodjob.destroy
    @goodjobs = Goodjob.where(article_id: params[:article_id])
    @articles = Article.all
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def set_article
    @article = Article.find(params[:article_id])
 end
end

app/helpers/goodjobs_helper.rb
module GoodjobsHelper
end

app/views/goodjobs/_goodjob.html.erb
<% if user_signed_in? %>
  <% if Goodjob.find_by(user_id: current_user.id, article_id: article.id) %>
  <% goodjob = Goodjob.find_by(user_id: current_user.id, article_id: article.id) %>
    <%= button_to unlike_path(article.id), method: :delete, class:"mb-10 btn beta", id: "goodjob-button", remote: true do %>
      <span>
        <%= article.goodjobs_counts %>
      </span>
      <span> Good</span>
    <% end %>
  <% else %>
    <%= button_to like_path(article.id), class:"btn alpha", id: "goodjob-button", remote: true do %>
      <span>
        <%= article.goodjobs_counts %>
      </span>
      <span> good</span>
    <% end %>
  <% end %>
<% else %>
  <% if article.goodjobs_count? %>
    <span>
      <%= article.goodjobs_counts %>
    </span>
    <span> good </span>
  <% else %>
    <span>
      <%= article.goodjobs_counts %>
    </span>
    <span>0 good</span>
  <% end %>    
<% end %>

app/views/goodjobs/create.js.erb
$("#goodjob-buttons").html("<%= j(render partial: 'goodjob', locals: { article: @article}) %>”);

app/views/goodjobs/destroy.js.erb
$("#goodjob-buttons").html("<%= j(render partial: 'goodjob', locals: { article: @article}) %>”);