config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'articles#index'
  get 'articles/search'

  resources :relationships

  resources :users, only: [:show, :edit, :update] do
    resources :favorites
    member do
      get :follow, :followers
    end
  end

  resources :articles do
    resources :goodjobs
  end
  post '/relationship/:follow_id', to: 'relationships#create', as: 'follow'
  post '/favorite/:article_id', to: 'favorites#create', as: 'love'
  delete '/favorite/:article_id', to: 'favorites#destroy', as: 'unlove'
  post 'articles/attach', to: 'articles#attach'
  post '/goodjob/:article_id', to: 'goodjobs#create', as: 'like'
  delete '/goodjob/:article_id', to: 'goodjobs#destroy', as: 'unlike'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :article, counter_cache: :favorite_counts
  belongs_to :user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_article, only:[:create, :destroy]
  before_action :search_article

  def index
    @articles = Article.includes(:user).order('created_at DESC')
    @favorites = Favorite.includes(:user)
  end

  def create
    @favorite = Favorite.create(user_id: current_user.id, article_id: @article.id)
    @favorites = Favorite.where(article_id: params[:article_id])
    @articles = Article.all
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, article_id: @article.id)
    @favorite.destroy
    @favorites = Favorite.where(article_id: params[:article_id])
    @articles = Article.all
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def set_article
    @article = Article.find(params[:article_id])
 end

 private

 def search_article
  @q = Article.ransack(params[:q])
 end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if Favorite.find_by(user_id: current_user.id, article_id: article.id) %>
  <% favorite = Favorite.find_by(user_id: current_user.id, article_id: article.id) %>
    <%= button_to unlove_path(article.id), method: :delete,class:"p-10 btn beta", id: "favorite-button", remote: true do %>
      <div class='favorite-info'>しおり</div>
    <% end %>
  <% else %>
    <%= button_to love_path(article.id), method: :post,class:"btn alpha", id: "favorite-button", remote: true do %>
      <div class='unfavorite-info'> ＋しおりに追加</div>
    <% end %>
  <% end %>
<% end %>

app/views/favorites/_favorite_articles1.html.erb
<% if articles.present? %>
  <div class='article-contents'>
    <% articles.each do |article| %>
    <% if  article.start? %>  
        <% if Favorite.find_by(user_id: current_user.id, article_id: article.id) %>
            <div class='article-content'>
              <div class='d-flex'>
                <div><%=link_to  user_path(article.user.id) do %>
                <% if article.user.user_image.attached? %>
                  <%=image_tag article.user.user_image, class: "rounded-circle", width:"30", height:"30" %>
                <% else %>
                  <span><%= article.user.nickname %></span>
                <% end %>
                <% end %>
                </div>が
                <span><%= l article.created_at %></span>に投稿
              </div>
              <%= link_to article_path(article.id),method: :get do %>
                <div class='article-content'>
                  <h3><%= article.name  %></h3>
                </div>
              <% end %>
            </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-buttons").html("<%= j(render partial: 'favorite', locals: { article: @article}) %>”);

app/views/favorites/destroy.js.erb
$("#favorite-buttons").html("<%= j(render partial: 'favorite', locals: { article: @article}) %>”);

app/views/favorites/index.html.erb
<%= render "shared/header"%>
<div class="margin">
</div>
<h2>しおり追加記事一覧</h2>
<div class="back">
  <% if @favorites.present? %>
   <%= render partial:"favorite_articles1", locals:{ articles: @articles, favorites: @favorites } %>
  <% else %>
    <h2>しおりに追加している記事はありません</h2>
  <% end %>
</div>

<%= render "shared/footer"%>