config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'articles#index'
  get 'articles/search'

  resources :relationships

  resources :users, only: [:show, :edit, :update] do
    resources :favorites
    member do
      get :follow, :followers
    end
  end

  resources :articles do
    resources :goodjobs
  end
  post '/relationship/:follow_id', to: 'relationships#create', as: 'follow'
  post '/favorite/:article_id', to: 'favorites#create', as: 'love'
  delete '/favorite/:article_id', to: 'favorites#destroy', as: 'unlove'
  post 'articles/attach', to: 'articles#attach'
  post '/goodjob/:article_id', to: 'goodjobs#create', as: 'like'
  delete '/goodjob/:article_id', to: 'goodjobs#destroy', as: 'unlike'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_one_attached :user_image
  has_many :follow_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :follows, through: :follow_relationships
  has_many :follower_relationships, foreign_key: "follow_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships


  def follow?(other_user)
    follow_relationships.find_by(follow_id: other_user.id)
  end

  def follow_create!(other_user)
    follow_relationships.create!(follow_id: other_user.id)
  end

  def follow_destroy!(other_user)
    follow_relationships.find_by(follow_id: other_user.id).destroy
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }
  validates :nickname, presence: true
  validates :birthday, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :search_article

  def show
    @articles = Article.includes(:user).order('created_at DESC')
    @articles_count = Article.joins(:user).group("users.nickname").order('count_all DESC').count 
    @tags = Article.tag_counts_on(:tags).order('count DESC')
  end

  def edit
    redirect_to user_path unless @user.id == current_user.id
  end

  def update
    if @user.update(user_params)
      render :show
    else
      render :edit
    end
  end

  def follow
    @user = User.find(params[:id])
    @users = @user.follows
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  def search
    @results = @q.result.includes(:user)  # 検索条件にマッチした記事の情報を取得
  end

  private

  def search_article
    @q = Article.ransack(params[:q])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_image, :nickname, :email, :password, :birthday)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header"%>
<div class=" align-items-center d-flex flex-column">
<%= form_with model: @user, url: user_path,method: :patch, class: 'align-items-center justify-content-center', local: true do |f| %>
<div class='form-wrap'>
  <div class='h3'>
      登録情報入力
  </div>

  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-group">
    <div class='d-flex'>
      <label class="form-text">ユーザーネーム</label>
      <label class="beta btn sm">必須</label>
    </div>
    <%= f.text_area :nickname, class:"form-control", id:"nickname", placeholder:"例) Search太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='d-flex'>
      <label class="form-text">メールアドレス</label>
      <label class="beta btn sm">必須</label>
    </div>
    <%= f.email_field :email, class:"form-control", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
      <div class='d-flex'>
      <label class="form-text">現在のパスワード確認</label>
      <label class="beta btn sm">必須</label>
    </div>
    <%= f.password_field :current_password, class:"input-default", autocomplete: "current-password" %>
  <div class="form-group">
    <div class='d-flex'>
      <label class="form-text">パスワード</label>
      <label class="beta btn sm">必須</label>
    </div>
    <%= f.password_field :password, class:"form-control", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='d-flex'>
      <label class="form-text">パスワード(確認)</label>
      <label class="beta btn sm">必須</label>
    </div>
    <%= f.password_field :password_confirmation, class:"form-control", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <%# プロフィール画像 %>
     <div class="form-group">
      <div class='d-flex'>
      <label class="form-text">プロフィール画像</label>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :user_image, id:"btn beta" %>
      </div>
    </div>
  <%# /プロフィール画像 %>
  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    </p>
  </div>
  <div class="form-group">
    <div class='d-flex'>
      <label class="form-text">生年月日</label>
      <label class="beta btn sm">必須</label>
    </div>
    <div class='d-flex'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
  <div class="form-group">
  </div>
  <div class='register-btn'>
    <%= f.submit "登録" ,class:"beta btn" %>
  </div>
</div>
<% end %>
</div>
<%= render "shared/footer"%>

app/views/users/followers.html.erb
<%= render "shared/header"%>
<h2 class='title'>
  フォロワー 一覧
</h2>
<style>
  table, th, td {
    border-collapse: collapse;
    border: 1px solid #ddd; 
    background-color: #fff
  }

  td {
    text-align: center;
    padding: 3vh;
    text-decoration: none;
    width: 37vw;
    font-size: x-large;
  }
</style>
<% if @users.present? %>
<table>
<tr>
<% @users.each do |user| %>
    <% if user.user_image.attached? %>
      <td>
      <%=link_to  user_path(user.id) do %>
      <%=image_tag user.user_image, class: "icon_middle_image"%></td>
      <td><%= user.nickname %></td>
      <% end %>
    <% else %>
    <td>イメージなし</td>
    <%=link_to  user_path(user.id) do %>
      <td><%= user.nickname %></td>
      <% end %>
    <% end %>
<% end %>
</tr>
</table>
<% else %>
  <h3 class='title'>現在フォロワーはいません</h3>
<% end %>
<%= render "shared/footer"%>

app/views/users/show.html.erb
<%= render "shared/header" , locals:{ articles: @articles }%>
<div class="margin">
</div>
<div class="d-flex flex-column flex-md-row  ">
  <div class="user-contents">
    <div class="user-image">
      <% if @user.user_image.present? %>
        <%=image_tag @user.user_image, class: "rounded-circle", width:"270", height:"270"%>
        <div class="user-info">
          <div class="h2 align-items-ceter "><%=@user.nickname%></div>
          <style>
            table, th, td {
              border-collapse: collapse;
              border: 1px solid #ddd; 
              background-color: #fff

            }

            td {
              text-align: center;
              padding: 3vh;
              text-decoration: none;
            }
          </style>
          <table class="table ">
          <% @articles_count.each_with_index do |article, i| %>
          <% if article.first == @user.nickname %>
          <tr>
            <td> <%= article.second %> </td>
            <td> <%= Article.where(user_id: @user.id).sum(:goodjobs_counts) %> </td>
            <td> <%= link_to followers_user_path(@user.id),method: :get do %>
            <%= @user.followers.count %>
            <% end %></td>
          </tr>
          <% end %>
          <% end %>
          <tr>
            <td> 投稿数 </td>
            <td> グッジョブ数 </td>
            <td> フォロワー数 </td>
          </tr>
          </table>
        </div>
      <% else %>
        <span><%=@user.nickname%></span>
      <% end %>
    </div>
    <div class="user-info">
      <div></div>
      <div></div>
      <div></div>
    </div>
    <% if user_signed_in? %>
    <div class="user-info">
      <% if @user.id == current_user.id %>
        <%= button_to "プロフィール編集", edit_user_path, method: :get , class: "beta btn"%>
      <% else %>
        <%= render 'relationships/follow' %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>  
  <div class="accordion " id="accordion-4">
  <div class="card">
    <div class="card-header" id="header-4a">
      <button class="btn btn-link beta" type="button" data-toggle="collapse" data-target="#card-4a" aria-expanded="true" aria-controls="card-4a">
       新着記事
      </button>
    </div>
    <div id="card-4a" class="collapse" aria-labelledby="header-4a" data-parent="#accordion-4">
      <div class="card-body">
        <%= render partial:"shared/user_articles1", locals:{ articles: @articles, user: @user } %>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="header-4b">
      <button class="btn btn-link beta" type="button" data-toggle="collapse" data-target="#card-4b" aria-expanded="true" aria-controls="card-4b">
       ツイート
      </button>
    </div>
    <div id="card-4b" class="collapse" aria-labelledby="header-4b" data-parent="#accordion-4">
      <div class="card-body">
        <%= render partial:"shared/user_articles2", locals:{ articles: @articles, user: @user } %>
      </div>
    </div>
  </div>


<%= render "shared/footer"%>