config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'articles#index'
  get 'articles/search'

  resources :relationships

  resources :users, only: [:show, :edit, :update] do
    resources :favorites
    member do
      get :follow, :followers
    end
  end

  resources :articles do
    resources :goodjobs
  end
  post '/relationship/:follow_id', to: 'relationships#create', as: 'follow'
  post '/favorite/:article_id', to: 'favorites#create', as: 'love'
  delete '/favorite/:article_id', to: 'favorites#destroy', as: 'unlove'
  post 'articles/attach', to: 'articles#attach'
  post '/goodjob/:article_id', to: 'goodjobs#create', as: 'like'
  delete '/goodjob/:article_id', to: 'goodjobs#destroy', as: 'unlike'
end

app/views/shared/_articles0.html.erb
<div class="tab_content" id="draft_content">
  <div class="tab_content_description">
      <% if articles.present? %>
        <div class='article-contents'>
          <% articles.each do |article| %>
            <% if  article.waiting? && article.user.id == current_user.id %>
              <div class='article-content'>
                  <div class='article-info'>
                    <div><%=link_to  user_path(article.user.id) do %>
                    <% if article.user.user_image.attached? %>
                      <%=image_tag article.user.user_image, class: "icon_small_image"%>
                    <% else %>
                      <span><%= article.user.nickname %></span>
                    <% end %>
                    <% end %>
                    </div>が
                    <span><%= l article.created_at %></span>に投稿
                  </div>
                  <div class='article-content'>
                    <%= link_to article_path(article.id),method: :get do %>
                    <h3><%=article.name  %></h3>
                    <% end %>
                  </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_articles1.html.erb
<div class="tab_content" id="article1_content">
  <div class="tab_content_description">
      <% if articles.present? %>
        <div class='article-contents'>
          <% articles.each do |article| %>
            <% if  article.start? %>  
              <div class='article-content'>
                  <div class='d-flex'>
                    <div><%=link_to  user_path(article.user.id) do %>
                    <% if article.user.user_image.attached? %>
                      <%=image_tag article.user.user_image, class: "rounded-circle", width:"30", height:"30" %>
                    <% else %>
                      <span><%= article.user.nickname %></span>
                    <% end %>
                    <% end %>
                    </div>が
                    <span><%= l article.created_at %></span>に投稿
                  </div>
                  <div class='article-content'>
                    <%= link_to article_path(article.id),method: :get do %>
                    <h3><%=article.name  %></h3>
                    <% end %>
                  <span><%=article.goodjobs_counts %>good</span>
                  <% if article.tags.present? %>
                    <div class='tags-table'>
                    <% @tags.each do |tag| %>
                       <%if article.tag_list.include?(tag.name) %>
                         <%= link_to "#{tag.name}(#{tag.taggings_count})", articles_path(tag: tag.name), class: "btn beta" %>
                      <% end %>
                    <% end %>
                    </div>
                  <% end %>
               </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_articles2.html.erb
<div class="tab_content" id="tweet_content">
  <div class="tab_content_description">
    <% if articles.present? %>
      <div class='tweet_contents'>
        <% articles.each do |article| %>
          <% if article.tweet? %>  
            <div class='tweet_content'>
              <div class='d-flex'>
                <div><%=link_to  user_path(article.user.id) do %>
                  <% if article.user.user_image.attached? %>
                    <%=image_tag article.user.user_image,  class: "rounded-circle", width:"30", height:"30"%>
                  <% else %>
                    <span><%= article.user.nickname %></span>
                  <% end %>
                <% end %>
                </div>が
                  <span><%= l article.created_at %></span>に投稿
               </div>
                <div class='article-content'>
                  <%= link_to article_path(article.id),method: :get do %>
                    <h3><%=markdown(article.text).html_safe  %></h3>
                  <% end %>
                  <span><%=article.goodjobs_counts %>good</span>
                  <% if article.tags.present? %>
                    <div class='tags-table'>
                    <% @tags.each do |tag| %>
                       <%if article.tag_list.include?(tag.name) %>
                        <%= link_to "#{tag.name}(#{tag.taggings_count})", articles_path(tag: tag.name), class: "btn beta" %>
                      <% end %>
                    <% end %>
                    </div>
                  <% end %>
                </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_fixed_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header>
<nav class='d-flex flex-column flex-md-row navbar-expand-md fixed-top align-items-center justify-content-between p-3 px-md-3 mb-4 beta border-bottom shadow-sm'>
  <div class='main-bar-contents'>
    <%= link_to 'SearchTweet', articles_path, method: :get, class:"h1 beta " %>
  </div>
  <%# ヘッダー操作ボタン %>
  <div class='d-flex flex-md-row align-items-center '>
    <% if user_signed_in? %>
    <%= search_form_for @q, url: articles_search_path do |f| %>
    <%= f.search_field :name_cont , class: "search-field"%>
    <%= f.submit '検索' %>
    <% end %>
  <% end %>
  <div class='d-flex px-md-1'>
      <ul class='d-flex row '>
          <% if user_signed_in? && current_user.id %>
            <div><%= link_to "しおり", user_favorites_path(current_user), method: :get , class: "p-2 btn beta"%> </div> 
            <div><%= link_to "+投稿", new_article_path, method: :get , class: "p-2 btn beta"%> </div> 
            <div><%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: "p-2 btn beta"%> </div> 
            <div><%= link_to current_user.nickname, user_path(current_user), method: :get, class: "p-2 btn beta" %></div> 
          <% else %>
            <div><%= link_to 'ログイン', new_user_session_path,method: :get, class: "p-2 btn beta" %></div>
            <div><%= link_to '新規登録', new_user_registration_path,method: :get , class: "p-2 btn beta" %></div>
            <div><%= link_to '検索', articles_path, method: :get, class: "p-2 btn beta" %></div> 
          <% end %>
      </ul>
    </div>
  </div>
<%# /ヘッダー操作ボタン %>
</nav>
</header>

app/views/shared/_footer.html.erb
<%# /下部広告部分 %>

<div class='d-flex flex-column flex-md-row align-items-center justify-content-center p-3 px-md-4 mb-3 alpha border-top shadow-sm'>
  <div class='d-flex flex-column align-items-center'>
    <div class='footer-details alpha'>
    </div>
    <div class='furima-details'>
      <h4 class='footer-content-head'>SearchTweetについて</h4>
      <ul>
        <li><%= link_to 'SearchTweetガイド', "#", class: "footer-link alpha" %></li>
        <li><%= link_to 'SearchTweetロゴ利用ガイドライン', "#", class: "footer-link alpha" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link alpha" %></li>
      </ul>
    </div>
  <%= link_to 'SearchTweet', articles_path,method: :get, class:"footer-icon-footer alpha" %>
  </div>
  
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header>
<nav class='d-flex flex-column flex-md-row navbar-expand-md align-items-center justify-content-between p-3 px-md-3 mb-4 beta border-bottom shadow-sm'>
  <div class='main-bar-contents'>
    <%= link_to 'SearchTweet', articles_path, method: :get, class:"h1 beta " %>
  </div>
  <%# ヘッダー操作ボタン %>
  <div class='d-flex flex-md-row align-items-center '>
    <% if user_signed_in? %>
    <%= search_form_for @q, url: articles_search_path do |f| %>
    <%= f.search_field :name_cont , class: "search-field"%>
    <%= f.submit '検索' %>
    <% end %>
  <% end %>
  <div class='d-flex px-md-1'>
      <ul class='d-flex'>
          <% if user_signed_in? && current_user.id %>
            <div><%= link_to "しおり", user_favorites_path(current_user), method: :get , class: "p-2 btn beta"%> </div> 
            <div><%= link_to "+投稿", new_article_path, method: :get , class: "p-2 btn beta"%> </div> 
            <div><%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: "p-2 btn beta"%> </div> 
            <div><%= link_to current_user.nickname, user_path(current_user), method: :get, class: "p-2 btn beta" %></div> 
          <% else %>
            <div><%= link_to 'ログイン', new_user_session_path,method: :get, class: "p-2 btn beta" %></div>
            <div><%= link_to '新規登録', new_user_registration_path,method: :get , class: "p-2 btn beta" %></div>
            <div><%= link_to '検索', articles_path, method: :get, class: "p-2 btn beta" %></div> 
          <% end %>
      </ul>
    </div>
  </div>
<%# /ヘッダー操作ボタン %>
</nav>
</header>

app/views/shared/_search_article.html.erb
<%= search_form_for @q, url: articles_search_path do |f| %>
<label >記事名</label>
<%= f.search_field :name_cont , class: "search-field"%>
<%= f.submit '検索' %>
<% end %>

app/views/shared/_show_btns.html.erb
    <ul class='show-btn'>
      <% if @article.user.id == current_user.id %>
        <li><%= button_to "編集", edit_article_path, method: :get , class: "register-red-btn"%> </li> 
        <li><%= button_to '削除', article_path, method: :delete, class: "register-red-btn" %>
        <li>                   
              <%= render partial: "goodjobs/goodjob", locals:{article: @article} %>
        </li> 
        <li><%= render partial: "favorites/favorite", locals:{article: @article} %></li>
      <% else %>
        <li>
          <div class='article-goodjob-counts' >
            <%= render partial: "goodjobs/goodjob", locals:{article: @article} %>
          </div>
        </li> 
        <li><%= render partial: "favorites/favorite", locals:{article: @article} %></li>
      <% end %>
    </ul>

app/views/shared/_tags.html.erb
<% tags.each do |tag| %>
  <%= link_to "#{tag.name}(#{tag.taggings_count})", articles_path(tag: tag.name) %>
<% end %>

app/views/shared/_user_articles0.html.erb
<div class="tab_content" id="article1_content">
  <div class="tab_content_description">
      <% if articles.present? %>
        <div class='article-contents'>
          <% articles.each do |article| %>
          <% if article.user.id == user.id %>
            <% if  article.wating? %>  
              <div class='article-content'>
                <%= link_to article_path(article.id),method: :get do %>
                  <div class='article-info'>
                    <div><%=article.user.nickname  %></div>が
                    <span><%= l article.created_at %></span>に投稿
                  </div>
                  <div class='article-content'>
                    <h3><%=article.name  %></h3>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_user_articles1.html.erb
<div class="tab_content" id="article1_content">
  <div class="tab_content_description">
      <% if articles.present? %>
        <div class='article-contents'>
          <% articles.each do |article| %>
          <% if article.user.id == user.id %>
            <% if  article.start? %>  
              <div class='article-content'>
                  <div class='article-info'>
                    <div><%=link_to  user_path(article.user.id) do %>
                      <span><%= article.user.nickname %></span>
                    <% end %>
                    </div>が
                    <span><%= l article.created_at %></span>に投稿
                  </div>
                  <div class='article-content'>
                    <%= link_to article_path(article.id),method: :get do %>
                    <h3><%=article.name  %></h3>
                    <% end %>
                  <span><%=article.goodjobs_counts %>good</span>
                  <% if article.tags.present? %>
                    <div class='tags-table'>
                    <% @tags.each do |tag| %>
                       <%if article.tag_list.include?(tag.name) %>
                         <%= link_to "#{tag.name}(#{tag.taggings_count})", articles_path(tag: tag.name), class: "btn beta" %>
                      <% end %>
                    <% end %>
                    </div>
                  <% end %>
               </div>
              </div>
            <% end %>
          <% end %>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_user_articles2.html.erb
<div class="tab_content" id="tweet_content">
  <div class="tab_content_description">
    <% if articles.present? %>
      <div class='tweet_contents'>
        <% articles.each do |article| %>
          <% if article.user.id == user.id %>
 <% if article.tweet? %>  
            <div class='tweet_content'>
              <div class='article-info'>
                <div><%=link_to  user_path(article.user.id) do %>
                    <span><%= article.user.nickname %></span>
                <% end %>
                </div>が
                  <span><%= l article.created_at %></span>に投稿
               </div>
                <div class='article-content'>
                  <%= link_to article_path(article.id),method: :get do %>
                    <h3><%=markdown(article.text).html_safe  %></h3>
                  <% end %>
                  <span><%=article.goodjobs_counts %>good</span>
                  <% if article.tags.present? %>
                    <div class='tags-table'>
                      <% @tags.each do |tag| %>
                       <%if article.tag_list.include?(tag.name) %>
                         <%= link_to "#{tag.name}(#{tag.taggings_count})", articles_path(tag: tag.name), class: "btn beta" %>
                      <% end %>
                    <% end %>
                    </div>
                  <% end %>
                </div>
            </div>
          <% end %>
        <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>